language: go
sudo: false
os:
- linux
- osx
go:
- 1.11
osx_image: xcode9.1
before_install:
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u golang.org/x/lint/golint
# - go get github.com/fzipp/gocyclo
before_script:
- GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
- test -z $(gofmt -s -l $GOFILES)
- go test ./...
- misspell -error -locale US $GOFILES
# - gocyclo -over 19 $GOFILES
- golint -set_exit_status $GOFILES