language: go
sudo: true
services:
- docker
env:
  matrix:
  - GO111MODULE=auto
matrix:
  include:
  - os: linux
    go: 1.12.x
    cache:
      directories:
      - "/home/travis/.cache/go-build"
  - os: osx
    go: 1.12.x
    cache:
      directories:
      - "/Users/travis/Library/Caches/go-build"
before_install:
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u golang.org/x/lint/golint
- go get github.com/fzipp/gocyclo
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get golang.org/x/tools/cmd/cover
before_script:
- GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then test -z $(gofmt -s -l $GOFILES); fi
- go test ./... -race -coverprofile=coverage.txt -covermode=atomic
- misspell -error -locale US $GOFILES
- gocyclo -over 20 $GOFILES
- golint -set_exit_status $GOFILES
- staticcheck ./pkg/*/*.go *.go
after_success:
- bash <(curl -s https://codecov.io/bash)
- make docker
before_deploy:
- make dist
deploy:
  provider: releases
  api_key:
    secure: T//YWgMmfNVPX2XxLQZ7xoWsEWUWWmn8sLWat3E91UdKT8YhmyaqPUl5pPAq0oiDc5/Ym5QzcUYdl6i5rR1ZbcWYzWsrx9T8CdgJaPmlRg1DF19tSHQUkfCxGC6chGX6U8iBjm+fpC3wCOhqBuEdRxdsE9Re0BbqjG4sbWM5HbL/pMe/1w6L2zk8QYrB1RI1zRpjIHWRBSLTUj8CteZ8Sr4reDMTjvQ/Mr0XeqDc6seBpsf0szRA6zbiXg1jmi/3dISA+f/6jzfjsFuy1b//5WoQ1RhwMU3KC1s+5nGfKHoM4Ov2MoDlpCB2TsiKInXjV3xS5yOK+eQUcRMNj4tCFY87TI/yLQQUnweKp7xLCyWDLcHsq4va9g0tQUOz8mQMZ96vFtwWX73GzUrI2Op3glebGw4umqOX/Ei+HzVGRzn/Q0wZkG2iMWm6NIVFmJALoTvGpnhSfx397JjhMHctEr7fEPjQFhXxSz1lgHaK7AV0JlkUui78w4EjSQFP1LY7LXn7dI3zEXlCDg8WUYPAc9/PXWUOhhtsRUbAoZOtbqNGjbaCYQDAwOyyLBuf5fAlXtwDkQYP1g2S/EmXuuOo+dxYRlbAZefLt1aPKREJqpbl+Avy3AP/cgMk5soYeFh8ojbqob8A+hJPhfexjVX+lVoB6VdUdSNBZN3YJc81q7k=
  file_glob: true
  file:
    - bin/auth-*
  on:
    repo: moov-io/auth
    tags: true
    go: 1.12.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
